version : '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: kalateam
      MYSQL_PASSWORD: escucha*2020Activa
      MYSQL_ROOT_PASSWORD: escucha*2020Activa

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 3307:80
volumes:
  db-data: {}
